# Generated by Django 5.2.3 on 2025-06-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='watch_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
