# Generated by Django 5.2.3 on 2025-07-09 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_created_at_alter_blog_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_unpublish_product', 'Разрешение на редактирование')], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, default='Пока нет описания', max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название блога'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publication',
            field=models.CharField(choices=[('moderation', 'На модерации'), ('approved', 'Опубликовано'), ('need_fix', 'Исправить'), ('rejected', 'Отклонено')], default='moderation', max_length=20, verbose_name='Статус проверки'),
        ),
    ]
