# Generated by Django 5.2.3 on 2025-07-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_options_alter_blog_blog_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('redact_status_blog', 'Изменение статуса публикации блога')], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
