# Generated by Django 5.2.3 on 2025-07-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('change_status_blog', 'Изменение статуса публикации блога'), ('change_topic_blog', 'Изменение темы блога')], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
