# Generated by Django 5.2.3 on 2025-07-20 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('auto', 'авто / мото'), ('travel', 'путешествия'), ('food', 'еда'), ('devices', 'гаджеты'), ('hobby', 'хобби / отдых / спорт')], default='auto', max_length=22, null=True, verbose_name='Тема блога')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='blog.topic', verbose_name='Тема блога'),
        ),
    ]
