# Generated by Django 5.2.3 on 2025-07-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_topic_blog_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
