# Generated by Django 5.2.3 on 2025-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='нет описания.', max_length=1200, null=True, verbose_name='описание'),
        ),
    ]
