# Generated by Django 5.2.3 on 2025-07-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_options_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Описание'),
        ),
    ]
